- CHANGELOG.md
- README.md
- caliban/cli.py
- caliban/docker.py
- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.gpu
- requirements-dev.txt
- scripts/build_dockerfiles.sh
This PR:
- modifies the Dockerfile to include `miniconda` in the base images
- adds a new Dockerfile that creates a slimmed-down base image for our GPU jobs. (The big difference here is that the tensorflow dependency is cut, saving us 600MB)
- adds support for `conda` dependencies via `environment.yml`, if it's present in the folder.
> Add Conda environment support to Caliban

- CHANGELOG.md
- caliban/docker.py
This fix mirrors the fix here: https://github.com/jhernand/openshift-monitoring/pull/5
> Fix Docker hanging on large user IDs

- README.md
- caliban/cli.py
- caliban/cloud/types.py
- caliban/gke/cli.py
- caliban/gke/cluster.py
- caliban/gke/constants.py
- caliban/gke/utils.py
- docs/index.rst
- tests/caliban/test_cli.py
- tests/caliban/test_docker.py
This PR:
- Fixes a couple of typos
- sorts imports and removes unused imports in various files
- adds a note to the README.md about how to check that Docker is installed and running correctly.
> clean up imports, add `docker run hello-world`

- caliban/docker.py
- dockerfiles/Dockerfile
This PR:
- fixes the python binary that `caliban notebook` points to (now that we use conda)
- adds `DEBIAN_FRONTEND=noninteractive` to the `apt-get` command, so that packages like `texlive` won't freeze and wait for you to specify a timezone.
> Fix `caliban notebook` and prep apt_packages for packages like texlive

- cloudbuild.json
- dockerfiles/Dockerfile
- scripts/cloudbuild.py
- scripts/cloudbuild_config.json
Please have a look. This adds a cloudbuild.json file that configures cloud build for our docker base images. This also adds a script to generate this file, and a configuration file for setting up our cloud builds. 
The config file in the PR has the url set to a test value for validation before we enable this for automatic builds.
> Add cloudbuild configuration for automatic docker image builds

- docs/getting_started/cloud.rst
Users need to complete this step to be able to push to the Container Registry. I believe that the error message tells you to do this if you hit a failure, but it's better to have it documented.
> Update `gcloud auth configure-docker` documentation

- caliban/util.py
- tests/caliban/test_util.py
This PR fixes the `close()` error reported in #29 , and forces the `docker build` step, and anything that uses `u.capture_stdout()`, to flush its buffer before proceeding. Otherwise the `docker build` output always appears at the end of any piped stdout.
> Flush buffered docker build stdout + fix close error from #29

- caliban/docker.py
- caliban/util.py
- setup.py
- tests/caliban/test_util.py
- tutorials/basic/mnist.py
This PR makes a few changes that allow us to use `caliban run` to execute scripts with (single) progress bars or other updating progress meters that use carriage returns to modify lines.
It's not PERFECT — if you have a progress bar and use `tqdm.write("HI!")` inside, for example, you'll trigger a newline, instead of the nice, flowing-upward output above the inner progress bar that you get when you run `tqdm` locally. But that is a challenge for another day.
I was able to package this pretty cleanly, I think, into `TqdmFile`, but it does require some fiddling in `capture_output` as well.
> Fix progress bar interactions in `caliban run` subprocesses

- CHANGELOG.md
- caliban/cli.py
- caliban/cloud/core.py
- docs/cloud/service_account.rst
- docs/explore/gcloud.rst
- docs/getting_started/cloud.rst
- docs/gke/prereq.rst
- docs/index.rst
This PR adds an additional authentication method for ai platform job submission. We can now grab creds directly from the `gcloud auth login` flow, instead of requiring that the user generate a service account key for authentication.
I've updated the documentation to reflect this new feature.
> Add support for gcloud auth login to enable job submission credentials

- caliban/config/__init__.py
I think this is a sufficient change for issue #40, but please have a look.
> fix for issue #40

- CHANGELOG.md
- caliban/cli.py
- caliban/config/__init__.py
- caliban/docker/build.py
- caliban/platform/notebook.py
- tests/caliban/config/test_config.py
- tutorials/basic/.calibanconfig.json
This PR gets us started with an approach for custom base images; this is inspired by @sagravat's work in #20, but I had changed so much about the project organization in the meantime that it felt appropriate to whip up this example.
@sagravat, would love your thoughts on how this feels to use!
The user can supply a `"base_image"` entry into `.calibanconfig.json` that can either be:
- a string, or
- a dict with "cpu" and "gpu" keys. Optional is fine, of course.
Any of the DLVM images will automatically expand. I took slight liberty by forcing the job mode into the name and adding a prefix. So we now have these DLVM options:
```
dlvm:pytorch-cpu
dlvm:pytorch-cpu-1.0
dlvm:pytorch-cpu-1.1
dlvm:pytorch-cpu-1.2
dlvm:pytorch-cpu-1.3
dlvm:pytorch-cpu-1.4
dlvm:tf-cpu
dlvm:tf-cpu-1.0 …
```
> Custom base image support in calibanconfig

- caliban/cli.py
Split `--docker_run_args` on any white space (and not just single spaces). See <https://docs.python.org/3.8/library/stdtypes.html#str.split> for details.
This does not introduce spurious empty arguments when multiple spaces are used to separate docker run args (as in `--volume  a:b`, with two spaces), and also ignores leading and trailing spaces (as in ` -v a:b`). The latter should also help with the warning described in <https://caliban.readthedocs.io/en/latest/recipes/local_dir.html>, "[...] if you pass -v instead of --volume [...]" since it allows using `-v` if you add a space in front of it.
> Split `--docker_run_args` on white space

- CONTRIBUTING.md
- Makefile
- docs/cli/caliban_shell.rst
I made two improvements to the documentation.
1. I made CONTRIBUTING.md more transparent around the sphinx-reload, and 
2. I added a warning in the caliban shell section about a potential pitfall of the automatic mounting of the user's $HOME directory
> Improved documentation

- dockerfiles/Dockerfile
Because pip does not recognize conda environments as proper virtual
environments, prior to this fix whenever it tried to install a package
in editable mode (with the -e flag), it would put the package in the
current working directory.  This caused problems because that directory
was overwritten when using caliban shell.
We fix this by setting the environmental variable PIP_SRC to be
/opt/conda/envs/caliban/pipsrc.  This tells pip to install the package
in that directory.
> [refs #00000] Allow editable installation of packages

- caliban/config/__init__.py
This PR paves the way for project, user and shared configurations across Caliban builds.
> Add structure to project and global calibanconfig schema

- caliban/resources/__init__.py
- caliban/util/__init__.py
- tests/caliban/util/test_util.py
This PR adds a new module that contains resources Caliban may need to access during execution. The accessor handles the case where the resource doesn't yet exist by returning None.
(`resource_filename` by itself returns the path, even if the file doesn't exist. This is useful if you want to write a resource, but not for an accessor.)
> Add new resource module, accessor function

- caliban/docker/build.py
- tests/caliban/docker/test_build.py
This PR adds a slightly clearer way of generating COPY commands inside a generated Dockerfile.
We also now have some slight tests here. I converted existing uses too, and reintroduced a few format strings.
> Add a clearer COPY command for better reuse in `caliban.docker.build`

- caliban/platform/gke/util.py
This addresses an error where we specify resource maxima for GKE clusters using quota information returned from the GCP compute API. The API can return a quota of zero for a given resource type, but requesting a limit of zero in the cluster creation API causes an error, so this change prevents setting a limit of zero for any resource.
> bugfix for https://github.com/google/caliban/issues/65

- caliban/docker/build.py
- tests/caliban/docker/test_build.py
This addresses issue #68, adding a newline to the end of `COPY` dockerfile directives generated by the `copy_command()` method in `build.py`. Thanks to @eschnett for finding this and the appropriate fix.
> fix for issue 68: adds newline in COPY directives generated by the copy_command method

- caliban/resources/caliban_launcher.py
- caliban/util/metrics.py
- tests/caliban/util/test_metrics.py
This (in progress) PR:
- adds the ability to inject a launcher script into the container, with the ability to intercept arguments, set environment variables and start up a service that will be available for the duration of the container's task.
This is the conclusion of a port of #35 .
> Add caliban launcher script to enable mlflow [in progress]

- COMMITTERS.md
- CONTRIBUTING.md
- README.md
This PR adds clearer information about how to contribute and send us bug reports and contributions.
Closes #48.
> Make it clearer how to contribute to Caliban

- cloudbuild.json
- docs/explore/base_image.rst
- scripts/cloudbuild.py
- scripts/cloudbuild_config.json
This PR adds support for generating caliban base images using different ubuntu base images, and also adds ubuntu 20.04 cpu base images to our cloudbuild configuration.
I ran this configuration manually, and the resulting tagged images can be found at `gcr.io/blueshift-playground/blueshift`
> Add ubuntu base image support to cloudbuild, add ubuntu 20.04 cpu base image

- setup.py
Just fixing a versioning issue for the `google-auth` package. This is for the `load_credentials_from_file` change in the auth package.
> updated google-auth dependency version

- setup.cfg
This PR just adds some `mypy` entries to `setup.cfg` to suppress warnings for third-party packages.
See https://mypy.readthedocs.io/en/stable/config_file.html?highlight=setup.cfg#the-mypy-configuration-file
> This PR adds mypy directives to setup.cfg to suppress third-party library warnings

- caliban/docker/build.py
This PR changes the default docker base image tags to reflect the cloudbuild naming scheme.
> This PR changes the default docker base image tags to reflect the cloudbuild naming scheme.

- caliban/platform/cloud/core.py
- caliban/platform/gke/cluster.py
- caliban/platform/run.py
- caliban/util/metrics.py
- tests/caliban/util/test_metrics.py
This PR prevents mlflow environment variables from being generated when there is no mlflow configuration in `.calibanconfig.json`.
> Prevent mlflow env vars from being generated when there is no mlflow config

- caliban/docker/build.py
This PR changes the docker ordering to add custom apt packages before installing python pip dependencies.
> re-order custom apt-packages before pip requirements (b/163169552)

- caliban/platform/gke/types.py
- caliban/platform/gke/util.py
- tests/caliban/platform/gke/test_types.py
- tests/caliban/platform/gke/test_util.py
This PR adds additional tests for `caliban.platform.gke.types` and `caliban.platform.gke.util`.
> add additional tests for gke.types and gke.util

- caliban/platform/gke/cli.py
- caliban/platform/gke/cluster.py
- caliban/platform/gke/util.py
This PR implements some minor bugfixes for the gke backend.
> minor bug fixes for gke

- caliban/resources/caliban_launcher.py
- tests/caliban/resources/test_caliban_launcher.py
This PR adds a non-none check to the caliban launcher script. This fixes a common error case where a user creates a `google.cloud.storage.Client()` instance, which fails if no gcp project can be determined automatically. We thus add a check in the launcher script to set a project via the `GOOGLE_CLOUD_PROJECT` environment variable only in the case where no default project can be determined.
> added non-none project check to caliban launcher

- docs/cli/caliban_build.rst
The documentation for `caliban build` included all options except the `no-cache` option.  I updated the doc to include it.
> update caliban build doc

- caliban/config/__init__.py
- caliban/util/metrics.py
- tests/caliban/util/test_metrics.py
This PR adds support for setting pubsub environment variables for use with UV's `MLFlowPubsubReporter`. These variables are configured via `.calibanconfig.json`.
> added uv-mlflow env vars for pubsub reporter

- docs/explore/base_image.rst
- docs/explore/calibanconfig.rst
This PR updates our docs to document our current base images, and document how to specify a custom base image in `.calibanconfig.json`
> update docs to reflect current base images, document how to specify custom base image

- .github/workflows/coverage.yml
- .github/workflows/pre-commit.yml
- .github/workflows/release.yml
- .github/workflows/workflow.yml
- CHANGELOG.md
- caliban/docker/build.py
- caliban/platform/run.py
- caliban/resources/caliban_launcher.py
- caliban/util/fs.py
- requirements-dev.txt
- setup.py
- tests/caliban/platform/gke/test_util.py
This PR:
- Upgrades `psycopg2-binary` and `pytest` to get tests passing again with
modern Python.
- Modifies `docker build` commands to get the built image ID via `--iidfile`
vs parsing the shell command output.
- adds `--platform linux/amd64` to `docker run` and `docker build` commands,
until we get support for `arm64` sorted out.
- fixes failure when GCP credentials aren't configured running in local mode.
> Fix image ID parsing in modern Docker

- caliban/docker/build.py
This PR fixes an issue where numeric group names are not allowed, seemingly on Ubuntu 22.04?
> Fix group name

- caliban/resources/caliban_launcher.py
- setup.cfg
This PR fixes a case identified by @georgematheos where `caliban run` fails when running in a project where `google-auth` is not installed. The solution is to use `find_spec` to check if google.auth is available on the classpath and use it only in that case.
> Fix failure on missing google.auth inside container
